#!/usr/bin/env python
import sys, re

USAGE = python extra_fasta.py fastafile ID.txt > new.fasta

if len(sys.argv) != 3:
    print USAGE

def fasta_select(files):
    d = {}
    with open(files) as f:
        for line in f:
            if line[0] == ">":
                name = re.search('>([\w-]+)',line).group(1)
                d[name] = ""
            else:
                d[name] += line
    return d
#    print "name:\n(%s)\nd[name]:\n(%s)" %(name,d[name])

if __name__ == "__main__":

    fastafile, id.txt = sys.argv[1:3]
    fasta_dealed = fasta_select(fastafile)

    with open(id.txt) as FastaList:
        for line in FastaList:
            targetID = line.strip()
            if targetID == "": continue
            if targetID in fasta_dealed:
                    seq = fasta_selecttargetID]
                    print ">%s\n%s" % (targetID, seq),
