#!/usr/bin/env python
while True:
    reply = input('Enter text:')
    if reply == 'stop':
        break
    elif not reply.isdigit():
        print('Bad!' * g)
    else:
        print(int(reply) ** 2)
print ('Bye')


test_keys =['name','age','gender','weight','hight']
test_values =['Hongten','20','M','55','170']
#使用zip来构造一个字典
print('字典中的key对应
test_dic =dict(zip(test_keys,test_values))
for key in test_dic:
print( key + ':' + test_dic[key])

log = open('log.txt', 'w')
print(1, 2, 3, file = log)
print(4, 5, 6, file = log)
log.close()
print(open('log.txt').read())

####格式化####
print（‘%s %s %s’ % ('A', 'B', 'C')）
print('{0} {1} {2}'.format('A', 'B', 'C'))

####行数据改为列数据，并用逗号隔开####
198
1989
266
...
转换成198,1989,266,...,
#!/usr/bin/env python
file = open(\r'test.txt', 'r')
result = list()
for line in file.readlines():
    line = line.strip()
    if not len(line) or line.startwith('#'):            #判断是否是空行或是注释行
        continue
    result.append(line)
print ','.join(result)

