#!/usr/bin/env python
>>> x = 'spam'
>>> while x:
...     print(x, end=' ')
...     x = X[l:]
...
spam pam am m

####
>>>a = 0; b = 10
>>>while a < b:
...    print(a, end = ' ')
...    a += 1
...
0 1 2 3 4 5 6 7 8 9


####
break contitue pass
while <test1>:
<statementsl>
if <test2>: break          # Exil loop now, skip else
if <t est3>: continue      # Go to top of loop now, to test1
else:
<statements2>              # Run if we didn't hit a 'break'


