#!/usr/bin/env python
import re, sys
file_exon = open('Genome.annotation_detail',"r")
bed_file = open('Genome_GO.xls',"w")
try:
    for line in file_exon.readlines():
        cols = line.strip().split("\t")
        if col[0] == "GeneID":
            print "line, file=bed_file"
        else:
            GO_ID = cols[0]
            Go_term = {1 : "Process", 2:"Function", 3:"Component"}
            key = Go_term.key()
            for x in key:
                i = cols[x]
#               print (i)
                GO_t = Go_term[x]
                for y in i.split(";"):
                    print ('{0}\t{1}\t{2}'.format(GO_ID,"\t".join(y.split("//")),GO_t,file=bed_file)
finally:
    file_exon.close()
    bed_file.close()



#!/usr/bin/env python

import sys
info=open(sys.argv[1])
diff=open(sys.argv[2])
out=open(sys.argv[3],'w')
d={}
for line in info:
	cols=line.strip().split("\t")
        a = line.strip().split("\t")
	d[cols[0]]="\t".join(a[1:])
info.close()

for line in diff:
	cols=line.strip().split("\t")
	if cols[1]=="gene_id":
		print >>out,(line.strip())
	else:
		print >>out,(d.get(cols[1],"-\t%s\t-"%cols[1])+"\t"+"\t".join(cols))
diff.close()
out.close()



